models:
  BaggingClassifier:
    n_estimators: [1,10, 50]
  GradientBoostingClassifier:
    n_estimators: [10,50]
    learning_rate: [0.1,0.5]
    subsample: [0.5,1.0]
    max_depth: [5,50]
  AdaBoostClassifier:
    algorithm: ['SAMME', 'SAMME.R']
    n_estimators: [1,10,50]
